apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v2alpha1.restaurant.programming-kubernetes.info
spec:
  insecureSkipTLSVerify: true
  group: restaurant.programming-kubernetes.info
  groupPriorityMinimum: 1000
  versionPriority: 25
  service:
    name: api
    namespace: pizza-apiserver
  version: v2alpha1
